####
#Configuration server with Git
####
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/DavidGallegosSanchez/config-repo/
          searchPaths: licensingservice,organizationservice
          username: native-cloud-apps
          password: Offended

####
#Classpath and file-based solution
####

#server:
#  port: 8888
#spring:
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          searchLocations: file:///Users/dagal/Projects/configuration-server/src/main/resources/config/licensingservice

